# frozen_string_literal: true

source 'https://rubygems.org'
gem 'acts_as_commentable'
gem 'acts-as-taggable-on'
gem 'agent_orange'
gem 'auto_html', git: 'https://github.com/fero46/auto_html.git'
gem 'aws-ses', '~> 0.6.0', require: 'aws/ses'
gem 'bourbon'
gem 'cancancan', '~> 1.9'
gem 'carrierwave'
gem 'clockwork'
gem 'coffee-rails'
gem 'color'
gem 'cookies_eu'
gem 'countries'
gem 'country_select'
gem 'daemons'
gem 'dalli'
gem 'devise'
gem 'devise-async'
gem 'devise-i18n'
gem 'domp'
gem 'dynamic_sitemaps'
gem 'fashion_fly_editor', git: 'git@github.org:fero46/fashion-fly-editor.git'
gem 'feedjira'
gem 'fog', require: 'fog/aws'
gem 'geocoder'
gem 'htmlentities'
gem 'i18n-country-translations'
gem 'jbuilder'
gem 'jquery-rails'
gem 'kaminari'
gem 'libxml-ruby'
gem 'lit'
gem 'mini_magick'
gem 'mysql2'
gem 'nokogiri'
gem 'pinterest-api'
gem 'puma'
gem 'rack-cors', require: 'rack/cors'
gem 'rack-utf8_sanitizer'
gem 'rails', '~> 5.1.4'
gem 'rails-i18n'
gem 'ratyrate', git: 'https://github.com/fero46/ratyrate.git'
gem 'redis'
gem 'redis-namespace'
gem 'rubyzip'
gem 'sass-rails'
gem 'settingslogic'
gem 'shareable'
gem 'sidekiq'
gem 'simple_hashtag', git: 'https://github.com/fero46/simple_hashtag'
gem 'sinatra', require: false
gem 'skylight'
gem 'tinymce-rails'
gem 'tinymce-rails-langs'
gem 'tokenizer'
gem 'uglifier'
gem 'unicode'
gem 'web-app-theme'
gem 'xmlrpc'

gem 'foundation-rails', '~> 5.5.0'
gem 'modernizr-rails'
group :doc do
  gem 'sdoc', require: false
end

gem 'exception_notification'
gem 'rack-attack'

gem 'capistrano', '3.5.0'
gem 'capistrano3-puma'
gem 'capistrano-bundler'
gem 'capistrano-rails'
gem 'capistrano-rails-collection'
gem 'capistrano-sidekiq'

gem 'omniauth'
gem 'omniauth-facebook'
gem 'omniauth-google-oauth2'
gem 'omniauth-pinterest'
gem 'omniauth-tumblr'
gem 'omniauth-twitter'

gem 'google-cloud-translate', '~> 2.0'
