development:
  app:
    name: FashionFly
    website: http://fashionfly.co
  company:
    name: HanseHype GmbH
    owner: "Ferhat Ziba, Firat Ziba"
    street: Schellerdamm 16
    city: "21079 Hamburg, Germany"
  oauth:
    facebook:
      id: x
      secret: x
    tumblr:
      id: x
      secret: x
    twitter:
      id: x
      secret: x
    google:
      id: x
      secret: x
test:
  app:
    name: FashionFly
    website: http://fashionfly.co
  company:
    name: HanseHype GmbH
    owner: "Ferhat Ziba, Firat Ziba"
    street: Schellerdamm 16
    city: "21079 Hamburg, Germany"
  oauth:
    facebook:
      id: x
      secret: x
    tumblr:
      id: x
      secret: x
    twitter:
      id: x
      secret: x
    google:
      id: x
      secret: x
production:
  app:
    name: FashionFly
    website: http://fashionfly.co
  company:
    name: HanseHype GmbH
    owner: "Ferhat Ziba, Firat Ziba"
    street: Schellerdamm 16
    city: "21079 Hamburg, Germany"
  oauth:
    facebook:
      id: x
      secret: x
    tumblr:
      id: x
      secret: x
    twitter:
      id: x
      secret: x
    google:
      id: x
      secret: x
