defaults: &defaults
  app:
    name: FashionFly
    website: http://fashionfly.co
  company:
    name: HanseHype GmbH
    owner: "Ferhat Ziba, Firat Ziba"
    street: Schellerdamm 16
    city: "21079 Hamburg, Germany"
  oauth:
    facebook:
      id: x
      secret: x
    tumblr:
      id: x
      secret: 104oqBPGO7nqXgnTMvcMwgKfms8OZDuwJo9IU9dICWEQZnAaXc
    twitter:
      id: XrPEL3EaKYiv08wqj5XRHZClF
      secret: byOPa31EjtlrcopJQRmQaY7GDWR3gKrzKteucbV9AAQSWI9QGO
    google:
      id: 160386295309-ragvk7g62vcfimrhv3vbcjktqujcmt4c.apps.googleusercontent.com
      secret: nva9FLxy1DPkhu01-ZW-2O7J
development:
  <<: *defaults
  oauth:
    facebook:
      id: x
      secret: x
    tumblr:
      id: x
      secret: x
    twitter:
      id: x
      secret: x
    google:
      id: x
      secret: x
test:
  <<: *defaults

production:
  <<: *defaults
